apiVersion: v1
kind: Service
metadata:
  name: redis-test-service
  labels:
    app: redis-test
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: redis-test

