name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run `kubegraf --web`
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: dropdown
    id: interface
    attributes:
      label: Interface
      description: Which interface were you using?
      options:
        - Terminal UI (TUI)
        - Web Dashboard
        - Both
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: KubeGraf Version
      description: Output of `kubegraf --version`
      placeholder: "v0.0.1"
    validations:
      required: true

  - type: input
    id: kubernetes
    attributes:
      label: Kubernetes Version
      description: Output of `kubectl version --short`
      placeholder: "v1.28.0"

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please copy and paste any relevant log output
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
